/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef SEC_CORE_DEFS_H
#define SEC_CORE_DEFS_H

#include <lemans_def.h>

#define APSS_BANKED_APSS_CPU_IPM_REG_BASE	(QTI_APSS_HM_BASE + 0x00000000)
#define APSS_BANKED_APC_SECURE_ADDR		(APSS_BANKED_APSS_CPU_IPM_REG_BASE + 0x0)
#define APSS_BANKED_APC_SECURE_RMSK		0x1

#define APSS_WDT_TMR1_APSS_WDT_REG_BASE		(QTI_APSS_HM_BASE + 0x00410000)
#define APSS_WDT_TMR1_WDOG_SECURE_ADDR		(APSS_WDT_TMR1_APSS_WDT_REG_BASE + 0x0)
#define APSS_WDT_TMR1_WDOG_SECURE_RMSK		0x1

#define APSS_SHARED_APSS_SHARED_REG_BASE	(QTI_APSS_HM_BASE + 0x00600000)
#define APSS_SHARED_KRYO_RVBARADDR_LO_ADDR	(APSS_SHARED_APSS_SHARED_REG_BASE + 0x101c)
#define APSS_SHARED_KRYO_RVBARADDR_HI_ADDR	(APSS_SHARED_APSS_SHARED_REG_BASE + 0x1020)
#define APSS_SHARED_SHR_SECURE_ADDR		(APSS_SHARED_APSS_SHARED_REG_BASE + 0x4)

#define APSS_ALIAS_0_APSS_CPU_IPM_REG_BASE	(QTI_APSS_HM_BASE + 0x00800000)
#define APSS_ALIAS_0_APC_SECURE_ADDR		(APSS_ALIAS_0_APSS_CPU_IPM_REG_BASE + 0x0)
#define APSS_ALIAS_0_APC_SECURE_RMSK		0x1

#define	APSS_ALIASn_APC_SECURE_OFFSET_TO_NEXT	0x10000
#define	APSS_ALIASn_APC_SECURE_MAX_INDEX	0x7

#define APSS_ALIAS_0_APSS_CL_IPM_REG_BASE	(QTI_APSS_HM_BASE + 0x00880000)
#define APSS_ALIAS_0_CL_SECURE_ADDR		(APSS_ALIAS_0_APSS_CL_IPM_REG_BASE + 0x0)
#define APSS_ALIAS_0_CL_SECURE_RMSK		0x1

#define APSS_ALIAS_1_APSS_CL_IPM_REG_BASE	(QTI_APSS_HM_BASE + 0x00890000)
#define APSS_ALIAS_1_CL_SECURE_ADDR		(APSS_ALIAS_1_APSS_CL_IPM_REG_BASE + 0x0)
#define APSS_ALIAS_1_CL_SECURE_RMSK		0x1

#define GOLD_SAW4_1_1_STS_REG_BASE		(QTI_APSS_HM_BASE + 0x00900c00)
#define GOLD_SAW4_SECURE_ADDR			(GOLD_SAW4_1_1_STS_REG_BASE + 0x0)
#define GOLD_SAW4_SECURE_RMSK			0x7

#define CL0_GOLD_APSS_KRYO_CLK_CTL_REG_BASE	(QTI_APSS_HM_BASE + 0x00a80000)
#define CL0_GOLD_PLL_SECURE_ADDR		(CL0_GOLD_APSS_KRYO_CLK_CTL_REG_BASE + 0x0)
#define CL0_GOLD_PLL_SECURE_RMSK		0x3

#define CL1_GOLD_APSS_KRYO_CLK_CTL_REG_BASE	(QTI_APSS_HM_BASE + 0x00a82000)
#define CL1_GOLD_PLL_SECURE_ADDR		(CL1_GOLD_APSS_KRYO_CLK_CTL_REG_BASE + 0x0)
#define CL1_GOLD_PLL_SECURE_RMSK		0x3

#define CL0_L3_APSS_KRYO_CLK_CTL_REG_BASE	(QTI_APSS_HM_BASE + 0x00a84000)
#define CL0_L3_PLL_SECURE_ADDR			(CL0_L3_APSS_KRYO_CLK_CTL_REG_BASE + 0x0)
#define CL0_L3_PLL_SECURE_RMSK			0x3

#define CL1_L3_APSS_KRYO_CLK_CTL_REG_BASE	(QTI_APSS_HM_BASE + 0x00a86000)
#define CL1_L3_PLL_SECURE_ADDR			(CL1_L3_APSS_KRYO_CLK_CTL_REG_BASE + 0x0)
#define CL1_L3_PLL_SECURE_RMSK			0x3

#define APSS_APSS_MISC_CLK_REG_BASE		(QTI_APSS_HM_BASE + 0x00aa0000)
#define APSS_MISC_CLK_SECURE_ADDR		(APSS_APSS_MISC_CLK_REG_BASE + 0x4)
#define APSS_MISC_CLK_SECURE_RMSK		0x1

#define APSS_APM_WRAP_REG_BASE			(QTI_APSS_HM_BASE + 0x00b00000)
#define APSS_PWR_APM_SECURE_ADDR		(APSS_APM_WRAP_REG_BASE + 0x24)
#define APSS_PWR_APM_SECURE_RMSK		0x3
#define APSS_PWR_MAS_SECURE_ADDR		(APSS_APM_WRAP_REG_BASE + 0x28)
#define APSS_PWR_MAS_SECURE_RMSK		0xf

#endif /* SEC_CORE_DEFS_H */
