/*
 * Copyright (c) 2015-2026, Renesas Electronics Corporation. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef RPC_REGISTERS_H
#define RPC_REGISTERS_H

#if defined(RCAR_LSI)
#define RPC_BASE	0xEE200000U
#elif defined(RZA3)
#define RPC_BASE	0x10060000U
#else
#error "SPI Multi I/O Bus Controller base address is not defined"
#endif

#define RPC_CMNCR	(RPC_BASE + 0x0000U)
#define RPC_SSLDR	(RPC_BASE + 0x0004U)
#define RPC_DRCR	(RPC_BASE + 0x000CU)
#define RPC_DRCMR	(RPC_BASE + 0x0010U)
#define RPC_DROPR	(RPC_BASE + 0x0018U)
#define RPC_DRENR	(RPC_BASE + 0x001CU)
#define RPC_SMCR	(RPC_BASE + 0x0020U)
#define RPC_SMCMR	(RPC_BASE + 0x0024U)
#define RPC_SMENR	(RPC_BASE + 0x0030U)
#define RPC_CMNSR	(RPC_BASE + 0x0048U)
#define RPC_DRDMCR	(RPC_BASE + 0x0058U)
#define RPC_DRDRENR	(RPC_BASE + 0x005CU)
#define RPC_PHYCNT	(RPC_BASE + 0x007CU)
#define RPC_PHYOFFSET1	(RPC_BASE + 0x0080U)
#define RPC_PHYOFFSET2	(RPC_BASE + 0x0084U)
#define RPC_PHYINT	(RPC_BASE + 0x0088U)

/* CMNCR field */
#define RPC_CMNCR_MD_POS	31
#define RPC_CMNCR_MD		(1u << RPC_CMNCR_MD_POS)
#define RPC_CMNCR_MOIIO3_POS	22
#define RPC_CMNCR_MOIIO3	(3u << RPC_CMNCR_MOIIO3_POS)
#define RPC_CMNCR_MOIIO2_POS	20
#define RPC_CMNCR_MOIIO2	(3u << RPC_CMNCR_MOIIO2_POS)
#define RPC_CMNCR_MOIIO1_POS	18
#define RPC_CMNCR_MOIIO1	(3u << RPC_CMNCR_MOIIO1_POS)
#define RPC_CMNCR_MOIIO0_POS	16
#define RPC_CMNCR_MOIIO0	(3u << RPC_CMNCR_MOIIO0_POS)
#define RPC_CMNCR_IO3FV_POS	14
#define RPC_CMNCR_IO3FV		(3u << RPC_CMNCR_IO3FV_POS)
#define RPC_CMNCR_IO2FV_POS	12
#define RPC_CMNCR_IO2FV		(3u << RPC_CMNCR_IO2FV_POS)
#define RPC_CMNCR_IO0FV_POS	8
#define RPC_CMNCR_IO0FV		(3u << RPC_CMNCR_IO0FV_POS)
#define RPC_CMNCR_IO_LOW	0u
#define RPC_CMNCR_IO_HIGH	1u
#define RPC_CMNCR_IO_KEEP	2u
#define RPC_CMNCR_IO_HIZ	3u
#define RPC_CMNCR_BSZ_POS	0
#define RPC_CMNCR_BSZ		(3u << RPC_CMNCR_BSZ_POS)
#define RPC_CMNCR_BSZ_SINGLE	0u
#define RPC_CMNCR_BSZ_DUAL	1u
#define RPC_CMNCR_BSZ_OCTA	1u
#define RPC_CMNCR_BSZ_HYPER	1u

/* SSLDR field */
#define RPC_SSLDR_SPNDL_POS	16
#define RPC_SSLDR_SPNDL		(7u << RPC_SSLDR_SPNDL_POS)
#define RPC_SSLDR_SLNDL_POS	8
#define RPC_SSLDR_SLNDL		(7u << RPC_SSLDR_SLNDL_POS)
#define RPC_SSLDR_SCKDL_POS	0
#define RPC_SSLDR_SCKDL		(7u << RPC_SSLDR_SCKDL_POS)

/* DRCR field */
#define RPC_DRCR_SSLN_POS	24
#define RPC_DRCR_SSLN		(1u << RPC_DRCR_SSLN_POS)
#define RPC_DRCR_RBURST_POS	16
#define RPC_DRCR_RBURST		(31u << RPC_DRCR_RBURST_POS)
#define RPC_DRCR_RCF_POS	9
#define RPC_DRCR_RCF		(1u << RPC_DRCR_RCF_POS)
#define RPC_DRCR_RBE_POS	8
#define RPC_DRCR_RBE		(1u << RPC_DRCR_RBE_POS)
#define RPC_DRCR_SSLE_POS	0
#define RPC_DRCR_SSLE		(1u << RPC_DRCR_SSLE_POS)

/* DREAR field */
#define RPC_DREAR_EAV_POS	16
#define RPC_DREAR_EAV		(255u << RPC_DREAR_EAV_POS)
#define RPC_DREAR_EAC_POS	0
#define RPC_DREAR_EAC		(7u << RPC_DREAR_EAC_POS)

/* DRCMR field */
#define RPC_DRCMR_CMD_POS	16
#define RPC_DRCMR_CMD		(255u << RPC_DRCMR_CMD_POS)
#define RPC_DRCMR_OCMD_POS	0
#define RPC_DRCMR_OCMD		(255u << RPC_DRCMR_OCMD_POS)

/* DROPR field */
#define RPC_DROPR_OPD3_POS	24
#define RPC_DROPR_OPD3		(255u << RPC_DROPR_OPD3_POS)
#define RPC_DROPR_OPD2_POS	16
#define RPC_DROPR_OPD2		(255u << RPC_DROPR_OPD2_POS)
#define RPC_DROPR_OPD1_POS	8
#define RPC_DROPR_OPD1		(255u << RPC_DROPR_OPD1_POS)
#define RPC_DROPR_OPD0_POS	0
#define RPC_DROPR_OPD0		(255u << RPC_DROPR_OPD0_POS)

/* DRENR field */
#define RPC_DRENR_CDB_POS	30
#define RPC_DRENR_CDB		(3u << RPC_DRENR_CDB_POS)
#define RPC_DRENR_OCDB_POS	28
#define RPC_DRENR_OCDB		(3u << RPC_DRENR_OCDB_POS)
#define RPC_DRENR_ADB_POS	24
#define RPC_DRENR_ADB		(3u << RPC_DRENR_ADB_POS)
#define RPC_DRENR_OPDB_POS	20
#define RPC_DRENR_OPDB		(3u << RPC_DRENR_OPDB_POS)
#define RPC_DRENR_DRDB_POS	16
#define RPC_DRENR_DRDB		(3u << RPC_DRENR_DRDB_POS)
#define RPC_DRENR_DB_4BIT	2u
#define RPC_DRENR_DB_1BIT	0u
#define RPC_DRENR_DME_POS	15
#define RPC_DRENR_DME		(1u << RPC_DRENR_DME_POS)
#define RPC_DRENR_CDE_POS	14
#define RPC_DRENR_CDE		(1u << RPC_DRENR_CDE_POS)
#define RPC_DRENR_OCDE_POS	12
#define RPC_DRENR_OCDE		(1u << RPC_DRENR_OCDE_POS)
#define RPC_DRENR_ADE_POS	8
#define RPC_DRENR_ADE		(15u << RPC_DRENR_ADE_POS)
#define RPC_DRENR_ADE_3BYTE	7u
#define RPC_DRENR_ADE_4BYTE	15u
#define RPC_DRENR_ADE_OPI	12u
#define RPC_DRENR_ADE_HYPER	4u
#define RPC_DRENR_ADE_NONE	0u
#define RPC_DRENR_OPDE_POS	4
#define RPC_DRENR_OPDE		(15u << RPC_DRENR_OPDE_POS)
#define RPC_DRENR_OPDE_NONE	0u
#define RPC_DRENR_OPDE_1BYTE	8u
#define RPC_DRENR_OPDE_2BYTE	12u
#define RPC_DRENR_OPDE_3BYTE	14u
#define RPC_DRENR_OPDE_4BYTE	15u

/* DRENR field */
#define RPC_DRENR_CDB_POS	30
#define RPC_DRENR_CDB		(3u << RPC_DRENR_CDB_POS)
#define RPC_DRENR_OCDB_POS	28
#define RPC_DRENR_OCDB		(3u << RPC_DRENR_OCDB_POS)
#define RPC_DRENR_ADB_POS	24
#define RPC_DRENR_ADB		(3u << RPC_DRENR_ADB_POS)
#define RPC_DRENR_OPDB_POS	20
#define RPC_DRENR_OPDB		(3u << RPC_DRENR_OPDB_POS)
#define RPC_DRENR_DRDB_POS	16
#define RPC_DRENR_DRDB		(3u << RPC_DRENR_DRDB_POS)
#define RPC_DRENR_DB_4BIT	2u
#define RPC_DRENR_DB_1BIT	0u
#define RPC_DRENR_DME_POS	15
#define RPC_DRENR_DME		(1u << RPC_DRENR_DME_POS)
#define RPC_DRENR_CDE_POS	14
#define RPC_DRENR_CDE		(1u << RPC_DRENR_CDE_POS)
#define RPC_DRENR_OCDE_POS	12
#define RPC_DRENR_OCDE		(1u << RPC_DRENR_OCDE_POS)
#define RPC_DRENR_ADE_POS	8
#define RPC_DRENR_ADE		(15u << RPC_DRENR_ADE_POS)
#define RPC_DRENR_ADE_3BYTE	7u
#define RPC_DRENR_ADE_4BYTE	15u
#define RPC_DRENR_ADE_OPI	12u
#define RPC_DRENR_ADE_HYPER	4u
#define RPC_DRENR_ADE_NONE	0u
#define RPC_DRENR_OPDE_POS	4
#define RPC_DRENR_OPDE		(15u << RPC_DRENR_OPDE_POS)
#define RPC_DRENR_OPDE_NONE	0u
#define RPC_DRENR_OPDE_1BYTE	8u
#define RPC_DRENR_OPDE_2BYTE	12u
#define RPC_DRENR_OPDE_3BYTE	14u
#define RPC_DRENR_OPDE_4BYTE	15u

/* DRDMCR field */
#define RPC_DRDMCR_DMCYC_POS	0
#define RPC_DRDMCR_DMCYC	(31u << RPC_DRDMCR_DMCYC_POS)

/* DRDRENR field */
#define RPC_DRDRENR_HYPE_POS	12
#define RPC_DRDRENR_HYPE	(7u << RPC_DRDRENR_HYPE_POS)
#define RPC_DRDRENR_SPI		0u
#define RPC_DRDRENR_DDR		5u
#define RPC_DRDRENR_OCTADDR	4u
#define RPC_DRDRENR_ADDRE_POS	8
#define RPC_DRDRENR_ADDRE	(1u << RPC_DRDRENR_ADDRE_POS)
#define RPC_DRDRENR_OPDRE_POS	4
#define RPC_DRDRENR_OPDRE	(1u << RPC_DRDRENR_OPDRE_POS)
#define RPC_DRDRENR_DRDRE_POS	0
#define RPC_DRDRENR_DRDRE	(1u << RPC_DRDRENR_DRDRE_POS)

/* PHYCNT field */
#define RPC_PHYCNT_CAL_POS		31
#define RPC_PHYCNT_CAL			(1u << RPC_PHYCNT_CAL_POS)
#define RPC_PHYCNT_ALT_ALIGN_POS	30
#define RPC_PHYCNT_ALT_ALIGN		(1u << RPC_PHYCNT_ALT_ALIGN_POS)
#define RPC_PHYCNT_OCTA_POS		22
#define RPC_PHYCNT_OCTA			(3u << RPC_PHYCNT_OCTA_POS)
#define RPC_PHYCNT_OCTA_DDR_ALT		1u
#define RPC_PHYCNT_OCTA_DDR_SEQ		2u
#define RPC_PHYCNT_EXDS_POS		21
#define RPC_PHYCNT_EXDS			(1u << RPC_PHYCNT_EXDS_POS)
#define RPC_PHYCNT_OCT_POS		20
#define RPC_PHYCNT_OCT			(1u << RPC_PHYCNT_OCT_POS)
#define RPC_PHYCNT_HS_POS		18
#define RPC_PHYCNT_HS			(1u << RPC_PHYCNT_HS_POS)
#define RPC_PHYCNT_CKSEL_POS		16
#define RPC_PHYCNT_CKSEL		(3u << RPC_PHYCNT_CKSEL_POS)
#define RPC_PHYCNT_WBUF2_POS		4
#define RPC_PHYCNT_WBUF2		(1u << RPC_PHYCNT_WBUF2_POS)
#define RPC_PHYCNT_WBUF_POS		2
#define RPC_PHYCNT_WBUF			(1u << RPC_PHYCNT_WBUF_POS)
#define RPC_PHYCNT_PHYMEM_POS		0
#define RPC_PHYCNT_PHYMEM		(3u << RPC_PHYCNT_PHYMEM_POS)
#define RPC_PHYCNT_SDR			0u
#define RPC_PHYCNT_DDR			1u
#define RPC_PHYCNT_HYPER		3u

/* PHYOFFSET1 field */
#define RPC_PHYOFFSET1_DDRTMG_POS	28
#define RPC_PHYOFFSET1_DDRTMG		(7u << RPC_PHYOFFSET1_DDRTMG_POS)
#define RPC_PHYOFFSET1_DDR		2u
#define RPC_PHYOFFSET1_SDR		3u

/* PHYOFFSET2 field */
#define RPC_PHYOFFSET2_OCTTMG_POS	8
#define RPC_PHYOFFSET2_OCTTMG		(7u << RPC_PHYOFFSET2_OCTTMG_POS)
#define RPC_PHYOFFSET2_SPI		4u
#define RPC_PHYOFFSET2_HYPER		4u
#define RPC_PHYOFFSET2_SPI_WBUF		0u
#define RPC_PHYOFFSET2_OSPI		3u

#endif /* RPC_REGISTERS_H */
