/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef QTI_ICBID_H
#define QTI_ICBID_H

enum icbid_master {
	ICBID_MASTER_MDP0 = 0,
	ICBID_MASTER_CDSP_PROC,
	ICBID_MASTER_LLCC,
	ICBID_MASTER_COMPUTE_NOC,
	ICBID_MASTER_MNOC_HF_MEM_NOC,
	ICBID_MASTER_CDSP_PROC_B,
	ICBID_MASTER_COMPUTE_NOC_1,
	ICBID_MASTER_COUNT,
	ICBID_MASTER_NONE = ICBID_MASTER_COUNT,
	ICBID_MASTER_SIZE = 0x7FFFFFFF /**< Force to 32 bits */
};

enum icbid_slave {
	ICBID_SLAVE_EBI1 = 0,
	ICBID_SLAVE_MNOC_HF_MEM_NOC,
	ICBID_SLAVE_LLCC,
	ICBID_SLAVE_CDSP_MEM_NOC,
	ICBID_SLAVE_CDSPB_MEM_NOC,
	ICBID_SLAVE_COUNT,
	ICBID_SLAVE_NONE = ICBID_SLAVE_COUNT,
	ICBID_SLAVE_SIZE = 0x7FFFFFFF /**< Force to 32 bits */
};

#endif /* QTI_ICBID_H */
