/*
 * Copyright (c) 2026 Qualcomm Innovation Center, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef SEC_CORE_DEFS_H
#define SEC_CORE_DEFS_H

#include "kodiak_def.h"

#define APSS_BANKED_APSS_CPU_IPM_REG_BASE	(QTI_APSS_HM_BASE + 0x00000000)
#define APSS_BANKED_APC_SECURE_ADDR		(APSS_BANKED_APSS_CPU_IPM_REG_BASE + 0x0)
#define APSS_BANKED_APC_SECURE_RMSK		0x1

#define APSS_WDT_TMR1_APSS_WDT_REG_BASE		(QTI_APSS_HM_BASE + 0x00410000)
#define APSS_WDT_TMR1_WDOG_SECURE_ADDR		(APSS_WDT_TMR1_APSS_WDT_REG_BASE + 0x0)
#define APSS_WDT_TMR1_WDOG_SECURE_RMSK		0x1

#define APSS_SHARED_APSS_SHARED_REG_BASE	(QTI_APSS_HM_BASE + 0x00600000)
#define APSS_SHARED_KRYO_RVBARADDR_LO_ADDR	(APSS_SHARED_APSS_SHARED_REG_BASE + 0x1c)
#define APSS_SHARED_KRYO_RVBARADDR_HI_ADDR	(APSS_SHARED_APSS_SHARED_REG_BASE + 0x20)
#define APSS_SHARED_SHR_SECURE_ADDR		(APSS_SHARED_APSS_SHARED_REG_BASE + 0x4)

#define APSS_ALIAS_0_APSS_CPU_IPM_REG_BASE	(QTI_APSS_HM_BASE + 0x00800000)
#define APSS_ALIAS_0_APC_SECURE_ADDR		(APSS_ALIAS_0_APSS_CPU_IPM_REG_BASE + 0x0)
#define APSS_ALIAS_0_APC_SECURE_RMSK		0x1

#define	APSS_ALIASn_APC_SECURE_OFFSET_TO_NEXT	0x10000
#define	APSS_ALIASn_APC_SECURE_MAX_INDEX	0x7

#define APSS_APSS_CL_IPM_REG_BASE		(QTI_APSS_HM_BASE + 0x00880000)
#define APSS_CL_SECURE_ADDR			(APSS_APSS_CL_IPM_REG_BASE + 0x0)
#define APSS_CL_SECURE_RMSK			0x1

#define GOLD_SAW4_1_1_STS_REG_BASE		(QTI_APSS_HM_BASE + 0x00901c00)
#define GOLD_SAW4_SECURE_ADDR			(GOLD_SAW4_1_1_STS_REG_BASE + 0x0)
#define GOLD_SAW4_SECURE_RMSK			0x7

#define SILVER_SAW4_1_1_STS_REG_BASE		(QTI_APSS_HM_BASE + 0x00900c00)
#define SILVER_SAW4_SECURE_ADDR			(SILVER_SAW4_1_1_STS_REG_BASE + 0x0)
#define SILVER_SAW4_SECURE_RMSK			0x7

#define GOLD_APSS_KRYO_CLK_CTL_REG_BASE		(QTI_APSS_HM_BASE + 0x00a82000)
#define GOLD_PLL_SECURE_ADDR			(GOLD_APSS_KRYO_CLK_CTL_REG_BASE + 0x40)
#define GOLD_PLL_SECURE_RMSK			0x3

#define SILVER_APSS_KRYO_CLK_CTL_REG_BASE	(QTI_APSS_HM_BASE + 0x00a80000)
#define SILVER_PLL_SECURE_ADDR			(SILVER_APSS_KRYO_CLK_CTL_REG_BASE + 0x40)
#define SILVER_PLL_SECURE_RMSK			0x3

#define L3_APSS_KRYO_CLK_CTL_REG_BASE		(QTI_APSS_HM_BASE + 0x00a84000)
#define L3_PLL_SECURE_ADDR			(L3_APSS_KRYO_CLK_CTL_REG_BASE + 0x40)
#define L3_PLL_SECURE_RMSK			0x3

#define APSS_APSS_MISC_CLK_REG_BASE		(QTI_APSS_HM_BASE + 0x00aa0000)
#define APSS_MISC_CLK_SECURE_ADDR		(APSS_APSS_MISC_CLK_REG_BASE + 0x4)
#define APSS_MISC_CLK_SECURE_RMSK		0x1

#define APSS_APM_WRAP_REG_BASE			(QTI_APSS_HM_BASE + 0x00b00000)
#define APSS_PWR_APM_SECURE_ADDR		(APSS_APM_WRAP_REG_BASE + 0x24)
#define APSS_PWR_APM_SECURE_RMSK		0x3
#define APSS_PWR_MAS_SECURE_ADDR		(APSS_APM_WRAP_REG_BASE + 0x28)
#define APSS_PWR_MAS_SECURE_RMSK		0xf

#endif /* SEC_CORE_DEFS_H */
