/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * ICB configuration hardware register address definitions for
 * Lemans (QCS9075).
 */

#ifndef QTI_ICBCFG_HWIO_H
#define QTI_ICBCFG_HWIO_H

/* Base addresses */
#define DDR_SS_BASE			0x09000000U
#define CORE_TOP_CSR_BASE		0x01f00000U
#define LPASS_BASE			0x02c00000U
#define SYSTEM_NOC_WRAPPER_BASE		0x01680000U
#define MMSS_NOC_WRAPPER_BASE		0x017a0000U

/*
 * TCSR: DDR channel-select mode fuse/register.
 * TCSR_TCSR_REGS_REG_BASE = CORE_TOP_CSR_BASE + 0x000c0000
 */
#define TCSR_REGS_BASE			(CORE_TOP_CSR_BASE + 0x000c0000U)
#define TCSR_TIMEOUT_INTR_CH2_CH4_OR_CH6_STATUS	(TCSR_REGS_BASE + 0x8088U)
#define TCSR_DDR_CH_SEL_MODE_BMSK	0x3U

/*
 * GEM_NOC dynamic-attribute registers.
 * GEM_NOC_REG_BASE = DDR_SS_BASE + 0x00100000
 */
#define GEM_NOC_BASE			(DDR_SS_BASE + 0x00100000U)

/* LOGUSEROV_LOW registers (log-user override enable) */
#define GEM_NOC_QNM_MNOC_HF0_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xe5028U)
#define GEM_NOC_QNM_MNOC_HF1_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xe6028U)
#define GEM_NOC_QNM_MNOC_SF0_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xe7028U)
#define GEM_NOC_QNM_MNOC_SF1_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xe8028U)
#define GEM_NOC_QNM_NSP_NOC0_0_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xe9028U)
#define GEM_NOC_QNM_NSP_NOC0_1_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xea028U)
#define GEM_NOC_QNM_NSP_NOC1_0_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xeb028U)
#define GEM_NOC_QNM_NSP_NOC1_1_DYNATTR_LOGUSEROV_LOW	(GEM_NOC_BASE + 0xec028U)

/* LOGUSERVAL_LOW registers (log-user override value) */
#define GEM_NOC_QNM_MNOC_HF0_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xe5030U)
#define GEM_NOC_QNM_MNOC_HF1_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xe6030U)
#define GEM_NOC_QNM_MNOC_SF0_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xe7030U)
#define GEM_NOC_QNM_MNOC_SF1_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xe8030U)
#define GEM_NOC_QNM_NSP_NOC0_0_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xe9030U)
#define GEM_NOC_QNM_NSP_NOC0_1_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xea030U)
#define GEM_NOC_QNM_NSP_NOC1_0_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xeb030U)
#define GEM_NOC_QNM_NSP_NOC1_1_DYNATTR_LOGUSERVAL_LOW	(GEM_NOC_BASE + 0xec030U)

/* GEM_NOC ALM TCU cache-index and main-control registers */
#define GEM_NOC_ALM_GPU_TCU_DYNATTR_CACHEINDEXVAL_LOW	(GEM_NOC_BASE + 0xad050U)
#define GEM_NOC_ALM_GPU_TCU_DYNATTR_MAINCTL_LOW		(GEM_NOC_BASE + 0xad008U)
#define GEM_NOC_ALM_PCIE_TCU_DYNATTR_CACHEINDEXVAL_LOW	\
	(GEM_NOC_BASE + 0xae050U)
#define GEM_NOC_ALM_PCIE_TCU_DYNATTR_MAINCTL_LOW	(GEM_NOC_BASE + 0xae008U)
#define GEM_NOC_ALM_SYS_TCU_DYNATTR_CACHEINDEXVAL_LOW	(GEM_NOC_BASE + 0xaf050U)
#define GEM_NOC_ALM_SYS_TCU_DYNATTR_MAINCTL_LOW	(GEM_NOC_BASE + 0xaf008U)

/*
 * MMSS_NOC (MNOC) dynamic-attribute registers.
 * MNOC_SERVICE_NETWORK_REG_BASE = MMSS_NOC_WRAPPER_BASE + 0x00000000 (HF)
 * MNOC_SERVICENETWORK_REG_BASE  = MMSS_NOC_WRAPPER_BASE + 0x00020000 (SF)
 */
#define MNOC_HF_BASE			(MMSS_NOC_WRAPPER_BASE + 0x00000000U)
#define MNOC_SF_BASE			(MMSS_NOC_WRAPPER_BASE + 0x00020000U)

/* MNOC HF LOGUSEROV_LOW */
#define MMSS_NOC_QNM_CAMNOC_HF0_DYNATTR_LOGUSEROV_LOW	(MNOC_HF_BASE + 0x7028U)
#define MMSS_NOC_QNM_MDP0_0_DYNATTR_LOGUSEROV_LOW	(MNOC_HF_BASE + 0x70a8U)
#define MMSS_NOC_QNM_MDP1_0_DYNATTR_LOGUSEROV_LOW	(MNOC_HF_BASE + 0x7128U)
#define MMSS_NOC_QNM_MDP0_1_DYNATTR_LOGUSEROV_LOW	(MNOC_HF_BASE + 0x71a8U)
#define MMSS_NOC_QNM_MDP1_1_DYNATTR_LOGUSEROV_LOW	(MNOC_HF_BASE + 0x7228U)

/* MNOC HF LOGUSERVAL_LOW */
#define MMSS_NOC_QNM_CAMNOC_HF0_DYNATTR_LOGUSERVAL_LOW	(MNOC_HF_BASE + 0x7030U)
#define MMSS_NOC_QNM_MDP0_0_DYNATTR_LOGUSERVAL_LOW	(MNOC_HF_BASE + 0x70b0U)
#define MMSS_NOC_QNM_MDP1_0_DYNATTR_LOGUSERVAL_LOW	(MNOC_HF_BASE + 0x7130U)
#define MMSS_NOC_QNM_MDP0_1_DYNATTR_LOGUSERVAL_LOW	(MNOC_HF_BASE + 0x71b0U)
#define MMSS_NOC_QNM_MDP1_1_DYNATTR_LOGUSERVAL_LOW	(MNOC_HF_BASE + 0x7230U)

/* MNOC SF LOGUSEROV_LOW */
#define MMSS_NOC_QNM_CAMNOC_ICP_DYNATTR_LOGUSEROV_LOW	(MNOC_SF_BASE + 0x7028U)
#define MMSS_NOC_QNM_CAMNOC_SF0_DYNATTR_LOGUSEROV_LOW	(MNOC_SF_BASE + 0x70a8U)
#define MMSS_NOC_QNM_VIDEO0_DYNATTR_LOGUSEROV_LOW	(MNOC_SF_BASE + 0x7128U)
#define MMSS_NOC_QNM_VIDEO1_DYNATTR_LOGUSEROV_LOW	(MNOC_SF_BASE + 0x7188U)
#define MMSS_NOC_QNM_VIDEO_CVP_DYNATTR_LOGUSEROV_LOW	(MNOC_SF_BASE + 0x7228U)
#define MMSS_NOC_QNM_VIDEO_V_CPU_DYNATTR_LOGUSEROV_LOW	(MNOC_SF_BASE + 0x72a8U)

/* MNOC SF LOGUSERVAL_LOW */
#define MMSS_NOC_QNM_CAMNOC_ICP_DYNATTR_LOGUSERVAL_LOW	(MNOC_SF_BASE + 0x7030U)
#define MMSS_NOC_QNM_CAMNOC_SF0_DYNATTR_LOGUSERVAL_LOW	(MNOC_SF_BASE + 0x70b0U)
#define MMSS_NOC_QNM_VIDEO0_DYNATTR_LOGUSERVAL_LOW	(MNOC_SF_BASE + 0x7130U)
#define MMSS_NOC_QNM_VIDEO1_DYNATTR_LOGUSERVAL_LOW	(MNOC_SF_BASE + 0x7190U)
#define MMSS_NOC_QNM_VIDEO_CVP_DYNATTR_LOGUSERVAL_LOW	(MNOC_SF_BASE + 0x7230U)
#define MMSS_NOC_QNM_VIDEO_V_CPU_DYNATTR_LOGUSERVAL_LOW	\
	(MNOC_SF_BASE + 0x72b0U)

/*
 * SYSTEM_NOC dynamic-attribute registers.
 * SNOC_SERVICE_NETWORK_REG_BASE = SYSTEM_NOC_WRAPPER_BASE + 0x00000000
 */
#define SNOC_BASE			(SYSTEM_NOC_WRAPPER_BASE + 0x00000000U)

/* SNOC LOGUSEROV_LOW */
#define SYSTEM_NOC_QHM_GIC_DYNATTR_LOGUSEROV_LOW	(SNOC_BASE + 0xa028U)
#define SYSTEM_NOC_QNM_LPASS_NOC_DYNATTR_LOGUSEROV_LOW	(SNOC_BASE + 0xd028U)
#define SYSTEM_NOC_XM_GIC_DYNATTR_LOGUSEROV_LOW	(SNOC_BASE + 0xf028U)

/* SNOC LOGUSERVAL_LOW */
#define SYSTEM_NOC_QHM_GIC_DYNATTR_LOGUSERVAL_LOW	(SNOC_BASE + 0xa030U)
#define SYSTEM_NOC_QNM_LPASS_NOC_DYNATTR_LOGUSERVAL_LOW (SNOC_BASE + 0xd030U)
#define SYSTEM_NOC_XM_GIC_DYNATTR_LOGUSERVAL_LOW	(SNOC_BASE + 0xf030U)

/* SNOC XM_GIC transaction-type LUT and main-control */
#define SYSTEM_NOC_XM_GIC_DYNATTR_TRTYPELUT_LOW	(SNOC_BASE + 0xf038U)
#define SYSTEM_NOC_XM_GIC_DYNATTR_MAINCTL_LOW		(SNOC_BASE + 0xf008U)

/*
 * LPASS_AG_NOC dynamic-attribute registers.
 * LPASS_AG_NOC_REG_BASE = LPASS_BASE + 0x01040000
 */
#define LPASS_AG_NOC_BASE		(LPASS_BASE + 0x01040000U)

#define LPASS_AG_NOC_QNM_LPASS_HW_AF_DYNATTR_MAINCTL_LOW \
					(LPASS_AG_NOC_BASE + 0x7008U)
#define LPASS_AG_NOC_QNM_LPASS_HW_AF_DYNATTR_TRTYPELUT_LOW \
					(LPASS_AG_NOC_BASE + 0x7038U)
#define LPASS_AG_NOC_QXM_LPASS_DSP_DYNATTR_MAINCTL_LOW \
					(LPASS_AG_NOC_BASE + 0x9008U)

#endif /* QTI_ICBCFG_HWIO_H */
